name: CI

on:
  push:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  install:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x64
          - os: ubuntu-24.04-arm64
            name: Linux ARM64
          - os: macos-14
            name: macOS ARM64
          - os: windows-latest
            name: Windows x64
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: test that dotslash is not preinstalled
        run: |
          if dotslash --version; then which dotslash; exit 1; fi
        shell: bash
      - name: install dotslash
        uses: ./
      - run: dotslash --version